    <style>
     .botoesfiltrocima {
		display: inline-block;
		height: 29px;
		margin-top: -6px;
		border-top-left-radius: 20px;
		border-top-right-radius: 20px;
		border-bottom-right-radius: 20px;
		border-bottom-left-radius: 20px;
		margin-right: 10px;
		float: left;
		width: 30px;
		padding: 3px 5px 5px 2px;
	}
	.botoesfiltrobaixo {
		display: inline-block;
		height: 29px;
		margin-top: -6px;
		border-top-left-radius: 20px;
		border-top-right-radius: 20px;
		border-bottom-right-radius: 20px;
		border-bottom-left-radius: 20px;
		margin-right: 10px;
		float: left;
		width: 30px;
		padding: 5px 5px 5px 2px;
	}
	
      .gmap3{
        margin: 20px auto;
        border: 1px dashed #C0C0C0;
        width: 95%;
        height: 370px;
      }
      .cluster{
  			color: #FFFFFF;
  			text-align:center;
  			font-family: 'Arial, Helvetica';
  			font-size:11px;
  			font-weight:bold;
      }
      .cluster-1{
        background-image:url(<?= IMAGENS; ?>m1.png);
        line-height:53px;
  			width: 53px;
  			height: 52px;
      }
      .cluster-2{
        background-image:url(<?= IMAGENS; ?>m2.png);
        line-height:53px;
  			width: 56px;
  			height: 55px;
      }
      .cluster-3{
        background-image:url(<?= IMAGENS; ?>m3.png);
        line-height:66px;
  			width: 66px;
  			height: 65px;
      }	
    </style>
    

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;<strong>Mapa de Escolas</strong></h3>
  	</div>
  	<div class="panel-body">
		<div align="center">
  		 
			<div class="panel panel-default" style="width: 99%" align="left">
				<div class="panel-heading" style="cursor:pointer;" onclick="mostraFiltros();">
					<h3 class="panel-title"><strong>Filtros &nbsp;</strong> <span style="font-style: italic; font-size: 12px;"> Clique aqui para adicionar filtros a pesquisa</span>
						<div style="float:left; margin-top:0px;"> 
							<button type="submit" title="Ocultar Filtros" id="btnesconde" style="display:none;" class="btn btn-default botoesfiltrocima">
								&nbsp;<span class="glyphicon glyphicon-chevron-up"></span>&nbsp; 
							</button>
							<button type="submit" title="Exibir Filtros" id="btnmostra" class="btn btn-default botoesfiltrobaixo">
								&nbsp;<span class="glyphicon glyphicon-chevron-down"></span>&nbsp;
							</button>
						</div>
					</h3>
			  	</div> 
			  	<div id="divfiltros" class="panel-body" style="display: none;" align="center">
			  		<!-- INICIO -Formulário de pesquisa -->
			  		<form action="/escola/lista">
						<div style="width: 99%;" align="left">
							<div class="row">
								<div class="col-xs-3">
							  		<label for="cod_escola">Código da Escola</label>
							    	<input type="text" id="cod_escola" name="cod_escola" class="form-control" placeholder="Código da Escola">
								</div>
								<div class="col-xs-3">
							  		<label for="nom_escola">Nome da Escola</label>
							    	<input type="text" id="nom_escola" name="nom_escola" class="form-control" placeholder="Nome da Escola">
								</div>
								<div class="col-xs-3">
							  		<label for="cod_rede">Rede</label>
							  		<?php
							  			echo Util::combo('cod_rede', $vars['dadosRede'], true, "Selecione..."); 
							  		?>
								</div>
							  	<div class="col-xs-3">
							  		<label for="cod_dependencia">Dependência</label>
							  		<?php
							  			echo Util::combo('cod_dependencia', $vars['dadosDependencia'], true, "Selecione..."); 
							  		?>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
							  		<label for="cod_regiao">Região</label>
							  		<?php
							  			echo Util::combo('cod_regiao', $vars['dadosRegiao'], true, "Selecione...", "carregaEstados(this);"); 
							  		?>
								</div>
								<div class="col-xs-3">
							  		<label for="cod_estado">Estado</label>
							  		<div id="divestados">
							  		<?php
							  			echo Util::combo('cod_estado', array(), false, "Selecione uma Região", ""); 
							  		?>
							  		</div>
								</div>
								<div class="col-xs-3">
							  		<label for="cod_municipio">Município</label>
							  		<div id="divmunicipios">
							  		<?php
							  			echo Util::combo('cod_municipio', array(), false, "Selecione um Estado", ""); 
							  		?>
							  		</div>
								</div>
							  	<div class="col-xs-3">
							  		<label for="cod_cat_dependencia">Categoria</label>
							  		<?php
							  			echo Util::combo('cod_cat_dependencia', $vars['dadosCategoria'], true, "Selecione..."); 
							  		?>
								</div>
							</div>
							<br>
							<button type="button" onclick="recuperaEscolas()" class="btn btn-default">Filtrar</button>
							<button type="button" onclick="limpar()" class="btn btn-default">Limpar</button>
						</div>
					</form>
				</div>
			</div>
		 <div id="mapa" class="gmap3"></div>
		 <div id="carregandoLista" style="height:370px;"> <img style="border:0px;" src="<?= IMAGENS; ?>carregando.gif"></div>
		</div>
	</div>
</div>       
<script type="text/javascript">
      $(function(){
  		$('#carregandoLista').show();
		$('#mapa').hide();
		          
	  	recuperaEscolas();
      });

      function recuperaEscolas(){
    	  $('#carregandoLista').show();
  		  $('#mapa').hide();

  		  //limpando o mapa
  		  $('#mapa').gmap3({clear:[]});
  		
          var cod_escola 			= $("#cod_escola").val();
          var nom_escola 			= $("#nom_escola").val();
          var cod_rede   			= $("#cod_rede").val();
          var cod_dependencia   	= $("#cod_dependencia").val();
          var cod_regiao   			= $("#cod_regiao").val();
          var cod_estado   			= $("#cod_estado").val();
          var cod_municipio   		= $("#cod_municipio").val();
          var cod_cat_dependencia	= $("#cod_cat_dependencia").val();
          
  		$.ajax({
  			type    : "POST",
  			async   : true,
  			dataType: "JSON",
  			url     : '/escola/carregaCoordenadas',
  			data	: { "cod_escola" 			: cod_escola,
  						"nom_escola" 			: nom_escola,
  						"cod_rede"	 			: cod_rede,
  						"cod_dependencia"		: cod_dependencia,
  						"cod_regiao"			: cod_regiao,
  						"cod_estado" 			: cod_estado,
  						"cod_municipio" 		: cod_municipio,
  						"cod_cat_dependencia"	: cod_cat_dependencia} })
  		 .done(function(result){
  			geraMapa(result);
  	  		$('#carregandoLista').hide();
  			$('#mapa').show();
  		 });
      }
      
      function geraMapa(escolas){
          $('#mapa').gmap3({
              map:{
                options:{
                  center:[-13.991083, -50.600978],
                  zoom: 4,
                  mapTypeId: google.maps.MapTypeId.ROADMAP,
                  streetViewControl: true
                }
              },
              marker:{
            	  values: escolas,
                  cluster:{
                    radius: 70,
                    events:{
                        click: function(overlay, event, context) {
                            var map = overlay.main.map;
                            var data = context.data;
                            map.panTo(data.latLng);
                            map.setZoom(map.getZoom() + 1);
                     	},
	                  	 mouseover: function(cluster, event){
	                  	   $(cluster.main.getDOMElement()).css('border', '1px solid #FF0000');
	                  	 },
	                  	 mouseout: function(cluster, event){
	                  	   $(cluster.main.getDOMElement()).css('border', '0px');
	                  	 }
                  	},
					// This style will be used for clusters with more than 0 markers
					0: {
					  content: '<div class="cluster cluster-1">CLUSTER_COUNT</div>',
						width: 53,
						height: 52
					},
					// This style will be used for clusters with more than 20 markers
					20: {
					  content: '<div class="cluster cluster-2">CLUSTER_COUNT</div>',
						width: 56,
						height: 55
					},
					// This style will be used for clusters with more than 50 markers
					50: {
					    content: '<div class="cluster cluster-3">CLUSTER_COUNT</div>',
						width: 66,
						height: 65
					}},
                	events:{
	                	click: function(marker, event, context){
		                	console.log(marker);
		                	console.log(event);
		                	console.log(context);
	                        var map = $(this).gmap3("get"),
	                          infowindow = $(this).gmap3({get:{name:"infowindow"}});
	                        if (infowindow){
	                          infowindow.open(map, marker);
	                          infowindow.setContent("<img src='<?= IMAGENS; ?>iconelupa2.png' title='Clique aqui para visualizar as informações da escola' onclick='exibirDetalhes(\"" + context.data + "\")' style='border:0px; width:20px; heigth:20px; cursor:pointer;')'><strong onclick='exibirDetalhes(\"" + context.data + "\")' style='cursor:pointer'>&nbsp;Visualizar Informações da escola</strong>");
	                        } else {
	                          $(this).gmap3({
	                            infowindow:
	                            {
	                              anchor:marker,
	                              options:{content: "<img src='<?= IMAGENS; ?>iconelupa2.png' title='Clique aqui para visualizar as informações da escola' onclick='exibirDetalhes(\"" + context.data + "\")' style='border:0px; width:20px; heigth:20px; cursor:pointer;')'><strong onclick='exibirDetalhes(\"" + context.data + "\")' style='cursor:pointer'>&nbsp;Visualizar Informações da escola</strong>"}
	                            }
	                          });
	                        }
	                      }
                	}
                }
            });
      }    

     function exibirDetalhes(cod_escola){
          window.location = "/escola/detalha/cod_escola/" + cod_escola;
     }   
      
      function limpar(){
      	$("#cod_escola").val('');          
      	$("#nom_escola").val('');          
      	$("#cod_rede").val('');            
      	$("#cod_dependencia").val('');     
      	$("#cod_regiao").val('');          
      	$("#cod_estado").val('');          
      	$("#cod_municipio").val('');       
      	$("#cod_cat_dependencia").val(''); 

      	carregaEstados('');

      	$('#mapa').gmap3({clear:[]});
      }

      function carregaEstados(regiao){
      	var cod_regiao = '';
          if(regiao){
  	    	cod_regiao = regiao.value;
          }
          $('#divestados').load( "/estado/carregaEstados/cod_regiao/" + cod_regiao );

          if(cod_regiao == ''){
          	carregaMunicipios(null);
          }
      }    

      function carregaMunicipios(estado){
      	var cod_estado = '';
          if(estado){
  	        cod_estado = estado.value;
          }
              
          $('#divmunicipios').load( "/municipio/carregaMunicipios/cod_estado/" + cod_estado );
      }    

      function mostraFiltros(){
          if($('#divfiltros:visible').length <= 0){
          	$('#divfiltros').show();
          	$('#btnesconde').show();
          	$('#btnmostra').hide();
          }else{
          	$('#divfiltros').hide();
          	$('#btnesconde').hide();
          	$('#btnmostra').show();
          }    
      }   
 </script>
