<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>Home</strong></h3>
  </div>
  <div class="panel-body" align="center">
  	<div style="display:inline-block;">
    	<img src="<?= IMAGENS; ?>escola1.png" class="img-responsive" style="float:left; border=:0px; width: 325px; margin-left:5px; margin-right:10px;">
		<div align="center">
			<div style="width: 99%;" style="float:left;">
			<p align="center"><b>Sistema de Consulta de informações das escolas de educação básica</b></p>
			
			<p align="justify">O sistema proposto tem por finalidade facilitar o acesso à informações das escolas públicas e particulares de educação 
							   básica do Brasil. Por meio dele será possível a visualização das informações das escolas de forma integrada e facilitada.</p>
			
			<p align="justify">O público alvo desse sistema é a população em geral que deseja consultar as informações sobre as instituições de ensino 
							   básico e possui dificuldade em encontrá-las pois as mesmas se encontram fragmentadas pela internet. O diferencial deste projeto
							   seria a possibilidade de acesso a todas essas informações em um só local, de forma integrada.</p>
			
			<p align="justify">As informações utilizadas no sistema foram retiradas do censo escolar, e estão disponíveis em forma de arquivos no portal de 
							   <a target="_blank" href="http://dados.gov.br/dataset/instituicoes-de-ensino-basico"><strong>Acesso a Informação do Governo Federal</strong></a>, 
							   as informações não serão alteradas, apenas tratadas e classificadas de forma a facilitar a pesquisa por parte do usuário.</p>
			
			<br>
			<div align="center">
				<button type="button" onclick="window.location='/escola/lista'" class="btn btn-default"><span class="glyphicon glyphicon-list"></span>&nbsp;<strong>Lista de Escolas</strong></button> &nbsp;
				<button type="button" onclick="window.location='/mapa/mapa'" class="btn btn-default"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;<strong>Mapa de Escolas</strong></button>
		    </div>
			</div>
		</div>
	</div>
  </div>
</div>
