<input type="hidden" id="cod_escola" name="cod_escola" value="<?= $vars['cod_escola']; ?>" />
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><strong>Dados da Escola</strong></h3>
  	</div>
  	<div class="panel-body">
		<ul id="myTab" class="nav nav-tabs">
		   <li><a href="/escola/lista" > Lista de Escolas </a></li>
		   <li class="active"><a href="#home" onclick="alteraAba('principal');" data-toggle="tab"> Informações Principais</a></li>
		   <li><a href="#ios" onclick="alteraAba('endereco');" data-toggle="tab">Endereço</a></li>
		</ul>  	
		<div id="div-conteudo-aba" align="center" style="border-left: 1px solid #DDDDDD; border-right: 1px solid #DDDDDD; border-bottom: 1px solid #DDDDDD;">
			<?php echo $vars['dadostela']; ?> 
		</div>
  	</div>
</div>
<script type="text/javascript">

	function alteraAba(tipo){
		$.ajax({
			type    : "POST",
			async   : true,
			url     : '/escola/detalha/tipo/'+ tipo + '/cod_escola/' + $('#cod_escola').val() })
		 .done(function(result){
			 $('#div-conteudo-aba').html(result);
		 });

	}
		
</script>