<link href="../../../public/css/datagrid/examples-offline.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.common.min.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.rtl.min.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.default.min.css" rel="stylesheet">

<script src="../../../public/javascript/datagrid/jquery.min.js"></script>
<script src="../../../public/javascript/datagrid/kendo.web.min.js"></script>
<script src="../../../public/javascript/datagrid/console.js"></script>        
<script src="../../../public/javascript/datagrid/products.js"></script>        
        
            <div id="grid" style="font-size: 11px;"></div>

            <script>
                $(document).ready(function() {

                    var escolas;

					$.ajax({
						type    : "POST",
						async   : false,
						dataType: "json",
						url     : '/projeto/escola/carregaEscolas'})
					 .done(function(result){
						 escolas = result;
					 });
                    
                    $("#grid").kendoGrid({
                        dataSource: {
                            data: escolas,
                            schema: {
                                model: {
                                    fields: {
                                    	cod_escola     : {type: "string" },
                                    	nom_escola     : {type: "string" },
                                    	nom_rede	   : {type: "string" },
                                    	nom_dependencia: {type: "string" }
                                    }
                                }
                            },
                            pageSize: 20
                        },
                        height: 470,
                        scrollable: true,
                        sortable: true,
                        filterable: false,
                        pageable: {
                            input: true,
                            numeric: false
                        },
                        columns: [
                            {field: "acao",title: "Ação", width: "5%" },
                            {field: "cod_escola", title: "Código", width: "10%" },
                            {field: "nom_escola", title: "Nome", width: "55%" },
                            {field: "nom_rede", title: "Rede", width: "15%" },
                            {field: "nom_dependencia", title: "Dependêcia", width: "15%" },
                        ]
                    });
                });
            </script>
