<link href="../../../public/css/datagrid/examples-offline.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.common.min.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.rtl.min.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.default.min.css" rel="stylesheet">

<script src="../../../public/javascript/datagrid/jquery.min.js"></script>
<script src="../../../public/javascript/datagrid/kendo.web.min.js"></script>
<script src="../../../public/javascript/datagrid/console.js"></script>        
<script src="../../../public/javascript/datagrid/products.js"></script>        
 
 <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>Lista de Escolas</strong></h3>
  </div>
  <div class="panel-body" align="center">
		<div id="grid" style="font-size: 11px; width: 95%;"></div>
  </div>
</div>       

<script>
    $(document).ready(function() {

        var escolas;

		$.ajax({
			type    : "POST",
			async   : false,
			dataType: "json",
			url     : '/escola/carregaEscolas'})
		 .done(function(result){
			 escolas = result;
		 });
        
        $("#grid").kendoGrid({
            dataSource: {
                data: escolas,
                schema: {
                    model: {
                        fields: {
                        	icone     	   : {type: "string" },
                        	cod_escola     : {type: "string" },
                        	nom_escola     : {type: "string" },
                        	nom_rede	   : {type: "string" },
                        	nom_dependencia: {type: "string" }
                        }
                    }
                },
                pageSize: 20
            },
            height: 470,
            scrollable: true,
            sortable: true,
            filterable: false,
            pageable: {
                input: true,
                numeric: false
            },
            columns: [
                {field: "icone",
                 template: "<img style='border:0px; cursor:pointer; width:20px; heigth:20px;' title='Clique para exibir informações da escola' src='<?= IMAGENS; ?>iconelupa2.png' onclick='exibeDetalhes(#: cod_escola #)'>", 
                 title: "Ação", 
                 width: "5%", 
                 attributes: { style: "text-align: center; "}},
                {field: "cod_escola", title: "Código", width: "10%", attributes: { style: "text-align: center; font-size: 14px;"}},
                {field: "nom_escola", title: "Nome", width: "55%", attributes: { style: "font-size: 14px; "}},
                {field: "nom_rede", title: "Rede", width: "15%", attributes: { style: "text-align: center;font-size: 14px; "} },
                {field: "nom_dependencia", title: "Dependêcia", width: "15%", attributes: { style: "text-align: center; font-size: 14px;"}},
            ]
        });
    });

    function exibeDetalhes(cod_escola){
        alert(cod_escola);
		console.log(cod_escola);
    }    

</script>

