<link href="../../../public/css/datagrid/examples-offline.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.common.min.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.rtl.min.css" rel="stylesheet">
<link href="../../../public/css/datagrid/kendo.default.min.css" rel="stylesheet">

<script src="../../../public/javascript/datagrid/kendo.web.min.js"></script>
<script src="../../../public/javascript/datagrid/console.js"></script>        
<script src="../../../public/javascript/datagrid/products.js"></script>        
 
 <style type="text/css">
	.botoesfiltrocima {
		display: inline-block;
		height: 29px;
		margin-top: -6px;
		border-top-left-radius: 20px;
		border-top-right-radius: 20px;
		border-bottom-right-radius: 20px;
		border-bottom-left-radius: 20px;
		margin-right: 10px;
		float: left;
		width: 30px;
		padding: 3px 5px 5px 2px;
	}
	.botoesfiltrobaixo {
		display: inline-block;
		height: 29px;
		margin-top: -6px;
		border-top-left-radius: 20px;
		border-top-right-radius: 20px;
		border-bottom-right-radius: 20px;
		border-bottom-left-radius: 20px;
		margin-right: 10px;
		float: left;
		width: 30px;
		padding: 5px 5px 5px 2px;
	}
</style>
 
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><strong>Lista de Escolas</strong></h3>
  	</div>
  	<div class="panel-body">
		<div align="center">
  		 
			<div class="panel panel-default" style="width: 99%" align="left">
				<div class="panel-heading" style="cursor:pointer;" onclick="mostraFiltros();">
					<h3 class="panel-title"><strong>Filtros</strong>
						<div style="float:left; margin-top:0px;"> 
							<button type="submit" title="Ocultar Filtros" id="btnesconde" style="display:none;" class="btn btn-default botoesfiltrocima">
								&nbsp;<span class="glyphicon glyphicon-chevron-up"></span>&nbsp; 
							</button>
							<button type="submit" title="Exibir Filtros" id="btnmostra" class="btn btn-default botoesfiltrobaixo">
								&nbsp;<span class="glyphicon glyphicon-chevron-down"></span>&nbsp;
							</button>
						</div>
					</h3>
			  	</div> 
			  	<div id="divfiltros" class="panel-body" style="display: none;" align="center">
			  		<!-- INICIO -Formulário de pesquisa -->
			  		<form action="/escola/lista">
						<div style="width: 99%;" align="left">
							<div class="row">
								<div class="col-xs-3">
							  		<label for="cod_escola">Código da Escola</label>
							    	<input type="text" id="cod_escola" name="cod_escola" class="form-control" placeholder="Código da Escola">
								</div>
								<div class="col-xs-3">
							  		<label for="nom_escola">Nome da Escola</label>
							    	<input type="text" id="nom_escola" name="nom_escola" class="form-control" placeholder="Nome da Escola">
								</div>
								<div class="col-xs-3">
							  		<label for="cod_rede">Rede</label>
							  		<?php
							  			echo Util::combo('cod_rede', $vars['dadosRede'], true, "Selecione..."); 
							  		?>
								</div>
							  	<div class="col-xs-3">
							  		<label for="cod_dependencia">Dependência</label>
							  		<?php
							  			echo Util::combo('cod_dependencia', $vars['dadosDependencia'], true, "Selecione..."); 
							  		?>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
							  		<label for="cod_regiao">Região</label>
							  		<?php
							  			echo Util::combo('cod_regiao', $vars['dadosRegiao'], true, "Selecione...", "carregaEstados(this);"); 
							  		?>
								</div>
								<div class="col-xs-3">
							  		<label for="cod_estado">Estado</label>
							  		<div id="divestados">
							  		<?php
							  			echo Util::combo('cod_estado', array(), false, "Selecione uma Região", ""); 
							  		?>
							  		</div>
								</div>
								<div class="col-xs-3">
							  		<label for="cod_municipio">Município</label>
							  		<div id="divmunicipios">
							  		<?php
							  			echo Util::combo('cod_municipio', array(), false, "Selecione um Estado", ""); 
							  		?>
							  		</div>
								</div>
							  	<div class="col-xs-3">
							  		<label for="cod_cat_dependencia">Categoria</label>
							  		<?php
							  			echo Util::combo('cod_cat_dependencia', $vars['dadosCategoria'], true, "Selecione..."); 
							  		?>
								</div>
							</div>
							<br>
							<button type="button" onclick="filtraGrid()" class="btn btn-default">Filtrar</button>
							<button type="button" onclick="limpar()" class="btn btn-default">Limpar</button>
						</div>
					</form>
					<!-- FIM - Formulário de pesquisa -->
				</div>
			</div>
			
			<!-- Grid de escolas -->
				<div id="carregandoLista" style="height:470px;"> <img style="border:0px;" src="<?= IMAGENS; ?>carregando.gif"></div>
			<div id="grid" style="font-size: 11px; width: 99%; "></div>
			<div id="semEscolas" style="font-size: 11px; width: 99%; "><strong style='font-size:20px;'>Nenhuma escola encontrada</strong></div>
		</div>
	</div>
</div>       

<script>
    $(document).ready(function() {
		$('#carregandoLista').show();
		$('#grid').hide();
		$('#semEscolas').hide();
		 
    	filtraGrid();
    });

    function limpar(){
    	$("#cod_escola").val('');          
    	$("#nom_escola").val('');          
    	$("#cod_rede").val('');            
    	$("#cod_dependencia").val('');     
    	$("#cod_regiao").val('');          
    	$("#cod_estado").val('');          
    	$("#cod_municipio").val('');       
    	$("#cod_cat_dependencia").val(''); 

    	carregaEstados('');
    	filtraGrid();
    }
    
    function filtraGrid(){
		$('#carregandoLista').show();
		$('#grid').hide();
		$('#semEscolas').hide();
		
        var cod_escola 			= $("#cod_escola").val();
        var nom_escola 			= $("#nom_escola").val();
        var cod_rede   			= $("#cod_rede").val();
        var cod_dependencia   	= $("#cod_dependencia").val();
        var cod_regiao   		= $("#cod_regiao").val();
        var cod_estado   		= $("#cod_estado").val();
        var cod_municipio   	= $("#cod_municipio").val();
        var cod_cat_dependencia	= $("#cod_cat_dependencia").val();
        var pesquisa			= "<?= $vars['pesquisa']; ?>";
        
		$.ajax({
			type    : "POST",
			async   : true,
			dataType: "json",
			url     : '/escola/carregaEscolas',
			data	: { "cod_escola" 			: cod_escola,
						"nom_escola" 			: nom_escola,
						"cod_rede"	 			: cod_rede,
						"cod_dependencia"		: cod_dependencia,
						"cod_regiao"			: cod_regiao,
						"cod_estado" 			: cod_estado,
						"cod_municipio" 		: cod_municipio,
						"cod_cat_dependencia"	: cod_cat_dependencia,
						"pesquisa"				: pesquisa} })
		 .done(function(result){
			 $('#carregandoLista').hide();
			 $('#grid').show();
			 $('#semEscolas').hide();
			 exibeGrid(result);
		 });
    }

    function exibeGrid(escolas){
        $('#grid').html('');
        
        if(!escolas){
	        $('#grid').html('');
	        $('#grid').hide();
	        $('#carregandoLista').hide();
	        $('#semEscolas').show();
	        return false;
        }
        
    	$("#grid").kendoGrid({
            dataSource: {
                data: escolas,
                schema: {
                    model: {
                        fields: {
                        	icone     	   		: {type: "string" },
                        	cod_escola     		: {type: "string" },
                        	nom_escola     		: {type: "string" },
                        	nom_rede	   		: {type: "string" },
                        	nom_dependencia		: {type: "string" },
                        	muncompleto			: {type: "string" }
                        }
                    }
                },
                pageSize: 20
            },
            height: 470,
            scrollable: true,
            sortable: true,
            filterable: false,
            pageable: {
                input: true,
                numeric: false
            },
            columns: [
                {field: "icone",
                 template: "<img style='border:0px; cursor:pointer; width:20px; heigth:20px;' title='Clique para exibir informações da escola' src='<?= IMAGENS; ?>iconelupa2.png' onclick='exibeDetalhes(#: cod_escola #)'>", 
                 title: "Ação", 
                 width: "5%", 
                 attributes: { style: "text-align: center; "}},
                {field: "cod_escola", title: "Código", width: "10%", attributes: { style: "text-align: center; font-size: 12px;"}},
                {field: "nom_escola", title: "Nome", width: "40%", attributes: { style: "font-size: 12px; "}},
                {field: "nom_rede", title: "Rede", width: "10%", attributes: { style: "text-align: center;font-size: 12px; "} },
                {field: "nom_dependencia", title: "Dependêcia", width: "10%", attributes: { style: "text-align: center; font-size: 12px;"}},
                {field: "muncompleto", title: "Município", width: "12%", attributes: { style: "font-size: 12px;"}},
                {field: "nom_distrito", title: "Distrito", width: "13%", attributes: { style: "font-size: 12px;"}}
            ]
        });
    
    }

    function exibeDetalhes(cod_escola){
         window.location = "/escola/detalha/cod_escola/" + cod_escola;
    }    

    function carregaEstados(regiao){
    	var cod_regiao = '';
        if(regiao){
	    	cod_regiao = regiao.value;
        }
        $('#divestados').load( "/estado/carregaEstados/cod_regiao/" + cod_regiao );

        if(cod_regiao == ''){
        	carregaMunicipios(null);
        }
    }    

    function carregaMunicipios(estado){
    	var cod_estado = '';
        if(estado){
	        cod_estado = estado.value;
        }
            
        $('#divmunicipios').load( "/municipio/carregaMunicipios/cod_estado/" + cod_estado );
    }    

    function mostraFiltros(){
        if($('#divfiltros:visible').length <= 0){
        	$('#divfiltros').show();
        	$('#btnesconde').show();
        	$('#btnmostra').hide();
        }else{
        	$('#divfiltros').hide();
        	$('#btnesconde').hide();
        	$('#btnmostra').show();
        }    
    }    

</script>

