<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
 <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <head>
		<link href="/public/css/datagrid/examples-offline.css" rel="stylesheet">
		<script src="/public/javascript/datagrid/jquery.min.js"></script>
		
		<!-- Includes do bootstrap -->
		<link rel="stylesheet" href="/public/css/bootstrap-3.1.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="/public/css/bootstrap-3.1.1/css/bootstrap-theme.min.css">
		<script src="/public/css/bootstrap-3.1.1/js/bootstrap.min.js"></script>
		
		<!--  includes mapa  -->
		<script src="http://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>
		<script type="text/javascript" src="/public/javascript/gmap3/gmap3.js"></script>

    </head>
    <body>
		<div id="geral">
		    <div id="cabecalho">
		    	<div style="display:inline-block;">
		            <img src="<?= IMAGENS; ?>Fundacao-Universa.png" style=" margin-top:15px; width: 176px; height: 40px; float:left;">
		            <div style="height: 80px; float:left; margin-left: 10px; margin-top: 0px;">
			            <span style="font-size: 40px; color:#555555;"><b>InfoEscola</b></span><br>
			            <span style="font-size: 20px; color:#555555;"><b>Sistema de Consulta de informações das Escolas</b></span>
		            </div>
		    	</div>
		    </div>
			<nav class="navbar navbar-default" role="navigation" style="margin-top: 15px;">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Menu</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="#">Menu</a>
			    </div>
			
			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav">
			        <li><a href="/index/index">Home</a></li>
			        <li><a href="/escola/lista">Lista de Escolas</a></li>
			        <li><a href="/mapa/mapa">Mapa de Escolas</a></li>
			      </ul>
			      <ul class="nav navbar-nav navbar-right">
			      <form class="navbar-form navbar-left" role="search">
			        <div class="form-group">
			          <input type="text" class="form-control" placeholder="Pesquisar Escolas">
			        </div>
			        <button type="submit" class="btn btn-default">&nbsp;<span class="glyphicon glyphicon-search"></span>&nbsp;</button>
			      </form>
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>	
		    <div id="conteudo" style="min-height: 75%;">
		        <div id="conteudo-principal" style="width: 100%;">
		            <?php 
			            if ( !file_exists($_caminho_view) ){
			            	echo "<h3 align='center'>Houve um erro. View nao existe.</h3>";
			            }else{
			            	require_once( $_caminho_view );
						}
		            ?>	        
		        </div>
		    </div>
		    <nav id="rodape" class="navbar navbar-default navbar-fixed-bottom" role="navigation">
			  <div class="container">
		     	<div style="margin-top:15px; text-align: center; font-size: 10px;"><b>Copyright © 2014 - Daniel Duarte - All rights reserved.</b></div>
			  </div>
			</nav>
		</div>        
    </body>
</html>