<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>Arquivos</strong></h3>
  </div>
  <div class="panel-body" align="center">
    <div class="well">Essa funcionalidade se encontra em <strong>construção</strong>, favor voltar mais tarde <strong> :)</strong> </div>
	<img src="<?= IMAGENS; ?>construcao.png" style="border:0px; width: 640px; height: 400px;">
  </div>
</div>
